import { Link, NavLink, Navigate, Outlet, useLocation } from 'react-router-dom'
import { useAuth } from './auth'
import type { Role } from './types'

export function Shell() { const { user, logout } = useAuth(); return <div className="shell"><header className="topbar"><Link className="wordmark" to="/app"><span className="mark">S</span> signal ledger</Link><nav aria-label="Primary navigation"><NavLink to="/app">Overview</NavLink><NavLink to="/app/tasks">Tasks</NavLink>{user?.role === 'admin' && <><NavLink to="/app/activities">Activity</NavLink><NavLink to="/app/analytics">Analytics</NavLink><NavLink to="/app/system">System</NavLink></>}</nav><div className="account"><span className="role-chip">{user?.role}</span><button className="text-button" onClick={() => void logout()}>Log out</button></div></header><main className="main"><Outlet /></main></div> }
export function Protected({ role }: { role?: Role }) { const { user, loading } = useAuth(); const location = useLocation(); if (loading) return <State kind="loading" text="Restoring your session…" />; if (!user) return <Navigate to="/login" state={{ from: location }} replace />; if (role && user.role !== role) return <Forbidden />; return <Outlet /> }
export function State({ kind, text }: { kind: 'loading' | 'empty' | 'error'; text: string }) { return <div className={`state state-${kind}`} role={kind === 'error' ? 'alert' : 'status'}><span className="state-dot" />{text}</div> }
export function Forbidden() { return <section className="center-panel"><p className="eyebrow">403 · private lane</p><h1>This view belongs to the control room.</h1><p>Your account can work with its own tasks, but not admin telemetry.</p><Link className="button" to="/app/tasks">Back to tasks</Link></section> }
export function PageHeader({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{children}</div> }
