import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { Landing, Login, Analytics, Tasks } from './pages'
import { State } from './components'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { AuthProvider } from './auth'
import userEvent from '@testing-library/user-event'
import { vi } from 'vitest'
import { getAccessToken } from './api'

test('landing explains the system thesis', () => { render(<MemoryRouter><Landing /></MemoryRouter>); expect(screen.getByText(/Trace the work/i)).toBeInTheDocument(); expect(screen.getByText(/LIVE ARCHITECTURE/i)).toBeInTheDocument() })
test('error state is announced accessibly', () => { render(<State kind="error" text="Reader unavailable" />); expect(screen.getByRole('alert')).toHaveTextContent('Reader unavailable') })
test('login submits credentials and stores access in memory', async () => { const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async (input,init)=>{ const url=String(input); if(url.includes('/refresh')) return new Response('',{status:401}); if(url.includes('/login')) return Response.json({access_token:'a',user_id:'u1',role:'member',token_type:'Bearer',expires_in:900}); return Response.json({}) }); const user=userEvent.setup();render(<MemoryRouter><AuthProvider><Login/></AuthProvider></MemoryRouter>);await user.click(screen.getByRole('button',{name:/sign in/i}));expect(getAccessToken()).toBe('a');expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/login'),expect.objectContaining({method:'POST'}));fetchMock.mockRestore() })
test('task status control calls update endpoint', async () => { const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async (input,init)=>{ const url=String(input);if(url.includes('/tasks?')) return Response.json({items:[{id:'t1',owner_id:'u1',title:'Ship',description:'',status:'todo',created_at:'',updated_at:''}]});return Response.json({id:'t1',owner_id:'u1',title:'Ship',description:'',status:'doing',created_at:'',updated_at:''}) }); const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const user=userEvent.setup();render(<MemoryRouter><QueryClientProvider client={client}><Tasks/></QueryClientProvider></MemoryRouter>);const select=await screen.findByRole('combobox');await user.selectOptions(select,'doing');expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/tasks/t1'),expect.objectContaining({method:'PUT'}));fetchMock.mockRestore() })
test('analytics renders populated projection metrics and chart data', async () => { const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{ const url=String(input);if(url.includes('summary')) return Response.json({total_events:6,created:3,updated:2,deleted:1,data_through:'2026-01-01T00:00:00Z',generated_at:'2026-01-01T00:00:00Z'});if(url.includes('timeseries')) return Response.json({points:[{day:'2026-01-01',created:3,updated:2,deleted:1}],data_through:'',generated_at:''});return Response.json({statuses:[{status:'done',count:4}],data_through:'',generated_at:''}) });const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<MemoryRouter><QueryClientProvider client={client}><Analytics/></QueryClientProvider></MemoryRouter>);expect(await screen.findByText('6')).toBeInTheDocument();expect(await screen.findByText('done')).toBeInTheDocument();expect(screen.getByText(/eventual/)).toBeInTheDocument();fetchMock.mockRestore() })
